// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfnY6ddp9StCAWSU1ZQ1zhiDeBzzqGDc',
    appId: '1:754637112411:web:47a4a2356c396818dcab7e',
    messagingSenderId: '754637112411',
    projectId: 'laser-magique-app-4192a',
    authDomain: 'laser-magique-app-4192a.firebaseapp.com',
    storageBucket: 'laser-magique-app-4192a.firebasestorage.app',
    measurementId: 'G-7PBVTSC6ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcvAxxklVjvff_D2hze7FVWcrXmQruLU',
    appId: '1:754637112411:android:da25a79b6b9040a8dcab7e',
    messagingSenderId: '754637112411',
    projectId: 'laser-magique-app-4192a',
    storageBucket: 'laser-magique-app-4192a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6sYnnU1AzN5fAvLBrt1gsqCYSezoO4aQ',
    appId: '1:754637112411:ios:c96c0e4cca9626cbdcab7e',
    messagingSenderId: '754637112411',
    projectId: 'laser-magique-app-4192a',
    storageBucket: 'laser-magique-app-4192a.firebasestorage.app',
    iosBundleId: 'com.thimotefetu.laserMagiqueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6sYnnU1AzN5fAvLBrt1gsqCYSezoO4aQ',
    appId: '1:754637112411:ios:c96c0e4cca9626cbdcab7e',
    messagingSenderId: '754637112411',
    projectId: 'laser-magique-app-4192a',
    storageBucket: 'laser-magique-app-4192a.firebasestorage.app',
    iosBundleId: 'com.thimotefetu.laserMagiqueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKfnY6ddp9StCAWSU1ZQ1zhiDeBzzqGDc',
    appId: '1:754637112411:web:67d5f85d51c92b0fdcab7e',
    messagingSenderId: '754637112411',
    projectId: 'laser-magique-app-4192a',
    authDomain: 'laser-magique-app-4192a.firebaseapp.com',
    storageBucket: 'laser-magique-app-4192a.firebasestorage.app',
    measurementId: 'G-K1HTNDGDVV',
  );
}
